### ISSUE TITLE
Question:  How hard would it be to add a "closeDiscardingChanges"?

### ISSUE THREAD

**Issue by npotts** [zardoy/extra-commands#4]
How hard would it be to add a feature(s) that:

* Closes the current buffer in way that does not does not prompt to save and does not keep the history
* Close *all* the open buffers in the same manner as above

I don't mind digging in, but I am not sure where to add such a 'feature'

**Comment by zardoy** [comment]
Sorry, I didn't get the notification neither via email nor webui, I just didn't see your issue.

> Closes the current buffer in way that does not does not prompt to save and does not keep the history

I'm a bit out of context, what buffers do you mean?

This is a VSCode extension, I don't know anything in API that is related to buffers.

Please provide minimal example/demo/whatever so I can better understand you.

**Comment by zardoy** [comment]
Here I maintain commands for general purpose usage, (most of them are for text editing though). If you want to add something language-specific, then you missed with the repo. However, fill free to discuss, in this case I'll reopen the issue.
